import { Product } from '../services/products/products.interface';

const firstProducts: Product[] = [
  {
    sku: 1,
    brand: 'Marca1',
    description: "Televisión 54''",
    image: 'http://www.lider.cl/catalogo/images/catalogo_no_photo.jpg',
    price: 80000,
  },
  {
    sku: 2,
    brand: 'Marca1',
    description: 'Microondas 120W',
    image: 'http://www.lider.cl/catalogo/images/catalogo_no_photo.jpg',
    price: 40000,
  },
  {
    sku: 3,
    brand: 'Marca1',
    description: 'Horno Gas Premium',
    image: 'http://www.lider.cl/catalogo/images/catalogo_no_photo.jpg',
    price: 30000,
  },
  {
    sku: 4,
    brand: 'Marca2',
    description: 'Refrigerador',
    image: 'http://www.lider.cl/catalogo/images/catalogo_no_photo.jpg',
    price: 20000,
  },
  {
    sku: 5,
    brand: 'Marca2',
    description: 'Cargador Smart Phone USB',
    image: 'http://www.lider.cl/catalogo/images/catalogo_no_photo.jpg',
    price: 15000,
  },
  {
    sku: 6,
    brand: 'Marca2',
    description: 'Lámpara Led USB',
    image: 'http://www.lider.cl/catalogo/images/catalogo_no_photo.jpg',
    price: 50000,
  },
  {
    sku: 7,
    brand: 'Marca2',
    description: 'Estufa Infrarrojo',
    image: 'http://www.lider.cl/catalogo/images/catalogo_no_photo.jpg',
    price: 80000,
  },
  {
    sku: 8,
    brand: 'Marca3',
    description: 'Calefont a gas',
    image: 'http://www.lider.cl/catalogo/images/catalogo_no_photo.jpg',
    price: 70000,
  },
  {
    sku: 9,
    brand: 'Marca3',
    description: 'Aspiradora sin bolsa',
    image: 'http://www.lider.cl/catalogo/images/catalogo_no_photo.jpg',
    price: 80000,
  },
  {
    sku: 10,
    brand: 'Marca3',
    description: 'Audífonos inalámbricos Galaxy',
    image: 'http://www.lider.cl/catalogo/images/catalogo_no_photo.jpg',
    price: 40000,
  },
  {
    sku: 11,
    brand: 'Marca4',
    description: 'Mouse USB',
    image: 'http://www.lider.cl/catalogo/images/catalogo_no_photo.jpg',
    price: 30000,
  },
  {
    sku: 12,
    brand: 'Marca4',
    description: 'Bicicleta Moutainbike Aro 29',
    image: 'http://www.lider.cl/catalogo/images/catalogo_no_photo.jpg',
    price: 40000,
  },
  {
    sku: 13,
    brand: 'Marca4',
    description: 'Hervidor Nuclear 1.7L',
    image: 'http://www.lider.cl/catalogo/images/catalogo_no_photo.jpg',
    price: 80000,
  },
  {
    sku: 14,
    brand: 'Marca5',
    description: 'Extractor de jugo Nutrimenos',
    image: 'http://www.lider.cl/catalogo/images/catalogo_no_photo.jpg',
    price: 80000,
  },
  {
    sku: 15,
    brand: 'Marca5',
    description: 'Minipimer MaxiHand 2000',
    image: 'http://www.lider.cl/catalogo/images/catalogo_no_photo.jpg',
    price: 60000,
  },
  {
    sku: 16,
    brand: 'Marca5',
    description: 'Consola Polystation 7',
    image: 'http://www.lider.cl/catalogo/images/catalogo_no_photo.jpg',
    price: 120000,
  },
  {
    sku: 17,
    brand: 'Marca6',
    description: 'Parlante Bluetooth LoudTeeth 1000',
    image: 'http://www.lider.cl/catalogo/images/catalogo_no_photo.jpg',
    price: 90000,
  },
  {
    sku: 18,
    brand: 'Marca6',
    description: 'Laptop Gamer YPS Bell',
    image: 'http://www.lider.cl/catalogo/images/catalogo_no_photo.jpg',
    price: 180000,
  },
  {
    sku: 39,
    brand: 'Marca6',
    description: 'Smartphone Teledummy II',
    image: 'http://www.lider.cl/catalogo/images/catalogo_no_photo.jpg',
    price: 120000,
  },
  {
    sku: 19,
    brand: 'Marca7',
    description: 'Neumaticos TripleMax 205/60/R16 Pack de 4 unidades',
    image: 'http://www.lider.cl/catalogo/images/catalogo_no_photo.jpg',
    price: 150000,
  },
  {
    sku: 20,
    brand: 'Marca7',
    description: 'Barra Antivuelco Universal para Camioneta 4x4',
    image: 'http://www.lider.cl/catalogo/images/catalogo_no_photo.jpg',
    price: 120000,
  },
  {
    sku: 21,
    brand: 'Marca7',
    description: 'Cooler 6 litros recargable',
    image: 'http://www.lider.cl/catalogo/images/catalogo_no_photo.jpg',
    price: 45000,
  },
  {
    sku: 22,
    brand: 'Marca8',
    description: 'Set de herramientas',
    image: 'http://www.lider.cl/catalogo/images/catalogo_no_photo.jpg',
    price: 65000,
  },
  {
    sku: 23,
    brand: 'Marca8',
    description: 'Taladro percutor 700W',
    image: 'http://www.lider.cl/catalogo/images/catalogo_no_photo.jpg',
    price: 120000,
  },
  {
    sku: 24,
    brand: 'Marca8',
    description: 'Lijadora Ultrasonido 800W',
    image: 'http://www.lider.cl/catalogo/images/catalogo_no_photo.jpg',
    price: 140000,
  },
  {
    sku: 25,
    brand: 'Marca9',
    description: 'Pack toallas mano Bambu-Menta',
    image: 'http://www.lider.cl/catalogo/images/catalogo_no_photo.jpg',
    price: 5000,
  },
  {
    sku: 26,
    brand: 'Marca9',
    description: 'Cafetera Picasso 2.6L',
    image: 'http://www.lider.cl/catalogo/images/catalogo_no_photo.jpg',
    price: 50000,
  },
  {
    sku: 27,
    brand: 'Marca9',
    description: 'Parrilla Eléctrica XXL',
    image: 'http://www.lider.cl/catalogo/images/catalogo_no_photo.jpg',
    price: 180000,
  },
  {
    sku: 28,
    brand: 'Marca10',
    description: 'Licuadora Expert Red',
    image: 'http://www.lider.cl/catalogo/images/catalogo_no_photo.jpg',
    price: 80000,
  },
  {
    sku: 29,
    brand: 'Marca10',
    description: 'Cama King Size Europea',
    image: 'http://www.lider.cl/catalogo/images/catalogo_no_photo.jpg',
    price: 140000,
  },
  {
    sku: 30,
    brand: 'Marca11',
    description: 'Cojín Velvet Pompones',
    image: 'http://www.lider.cl/catalogo/images/catalogo_no_photo.jpg',
    price: 25000,
  },
  {
    sku: 31,
    brand: 'Marca11',
    description: 'Coche Travel System Tesla',
    image: 'http://www.lider.cl/catalogo/images/catalogo_no_photo.jpg',
    price: 35000,
  },
  {
    sku: 32,
    brand: 'Marca12',
    description: 'Control Inalámbrico Robot',
    image: 'http://www.lider.cl/catalogo/images/catalogo_no_photo.jpg',
    price: 65000,
  },
  {
    sku: 40,
    brand: 'Marca12',
    description: 'Freezer Horizontal 99L',
    image: 'http://www.lider.cl/catalogo/images/catalogo_no_photo.jpg',
    price: 120000,
  },
  {
    sku: 33,
    brand: 'Marca13',
    description: "Carpa de Playa 'El Yaque'",
    image: 'http://www.lider.cl/catalogo/images/catalogo_no_photo.jpg',
    price: 50000,
  },
  {
    sku: 34,
    brand: 'Marca13',
    description: 'Bolso Travel Duffle 80L',
    image: 'http://www.lider.cl/catalogo/images/catalogo_no_photo.jpg',
    price: 40000,
  },
  {
    sku: 35,
    brand: 'Marca14',
    description: 'Colchón inflable 2 plazas',
    image: 'http://www.lider.cl/catalogo/images/catalogo_no_photo.jpg',
    price: 20000,
  },
  {
    sku: 36,
    brand: 'Marca14',
    description: 'Cocinilla a gas Mini',
    image: 'http://www.lider.cl/catalogo/images/catalogo_no_photo.jpg',
    price: 25000,
  },
  {
    sku: 37,
    brand: 'Marca15',
    description: "Tabla Surf 7'11 Pipeline",
    image: 'http://www.lider.cl/catalogo/images/catalogo_no_photo.jpg',
    price: 180000,
  },
  {
    sku: 38,
    brand: 'Marca15',
    description: 'Set asado 4 piezas',
    image: 'http://www.lider.cl/catalogo/images/catalogo_no_photo.jpg',
    price: 40000,
  },
  {
    sku: 850,
    brand: 'Marca Acme',
    description: 'Libélula livea 20W',
    image: 'http://www.lider.cl/catalogo/images/catalogo_no_photo.jpg',
    price: 15000,
  },
  {
    sku: 888,
    brand: 'Marca Acme',
    description: 'Cable de teléfono inteligente 100 metros',
    image: 'http://www.lider.cl/catalogo/images/catalogo_no_photo.jpg',
    price: 10000,
  },
  {
    sku: 39,
    brand: 'Marca Acme',
    description: 'Plan directv 50 mb',
    image: 'http://www.lider.cl/catalogo/images/catalogo_no_photo.jpg',
    price: 5000,
  },
  {
    sku: 40,
    brand: 'Marca Acme',
    description: 'Muñeca lipo 30',
    image: 'http://www.lider.cl/catalogo/images/catalogo_no_photo.jpg',
    price: 18000,
  },
  {
    sku: 150,
    brand: 'Marca Acme',
    description: 'luces crypto 80W',
    image: 'http://www.lider.cl/catalogo/images/catalogo_no_photo.jpg',
    price: 9000,
  },
  {
    sku: 500,
    brand: 'Marca Acme',
    description: 'luces crypto 120W',
    image: 'http://www.lider.cl/catalogo/images/catalogo_no_photo.jpg',
    price: 29990,
  },
  {
    sku: 600,
    brand: 'Marca Acme',
    description: 'Earpods cimul',
    image: 'http://www.lider.cl/catalogo/images/catalogo_no_photo.jpg',
    price: 129990,
  },
  {
    sku: 41,
    brand: 'Ferrati',
    description: 'Automóvil eléctrico para niños 8 años',
    image: 'http://www.lider.cl/catalogo/images/catalogo_no_photo.jpg',
    price: 389990,
  },
  {
    sku: 42,
    brand: 'Televi',
    description: 'Televisión 75 pulgadas 8k libre región, Timeplex',
    image: 'http://www.lider.cl/catalogo/images/catalogo_no_photo.jpg',
    price: 1200000,
  },
  {
    sku: 43,
    brand: 'Televi',
    description: 'Televisión 60 pulgadas 4k libre región, Maracaná',
    image: 'http://www.lider.cl/catalogo/images/catalogo_no_photo.jpg',
    price: 500000,
  },
  {
    sku: 44,
    brand: 'Televi',
    description: 'Televisión 80 pulgadas QLED libre región, Maracaná',
    image: 'http://www.lider.cl/catalogo/images/catalogo_no_photo.jpg',
    price: 389990,
  },
  {
    sku: 45,
    brand: 'Televi',
    description: 'Televisión 80 QLED, Rio',
    image: 'http://www.lider.cl/catalogo/images/catalogo_no_photo.jpg',
    price: 2500000,
  },
];

export default firstProducts;
